### ISSUE TITLE
Request to import isort-like linter for source code (via ruff)

### ISSUE THREAD

**Issue by gbaian10** [thewh1teagle/kokoro-onnx#146]
### Describe the feature

We just need to add the following content to `pyproject.toml`:

```toml
[tool.ruff]
output-format = "concise"
show-fixes = true

[tool.ruff.lint]
extend-select = ["I", "UP"]
```

Some of these are my personal preferences. If you want a minimal setup for importing the `isort` feature, you only need the following content:

```toml
extend-select = ["I"]
```

---

Then we just need to run `ruff check --fix`, and Ruff will take care of everything for us.
